usage: pycdc [-h] {search,recommend,occasions,budgets} ...
pycdc: error: argument command: invalid choice: 'C:\\Users\\Fores\\OneDrive\\Documents\\OpenCode Project\\HG锁区\\HG服务器锁定v2.1.exe_extracted\\HG_Firewall.pyc' (choose from search, recommend, occasions, budgets)
